ktor {
  deployment {
    port = 8081
    port = ${?PORT}
  }

  database {
    url = "jdbc:mysql://localhost:3306/homegym"
    user = "homegym_user"
    password = "1234"
    driver = "com.mysql.cj.jdbc.Driver"
  }

  jwt {
    secret = "super-secret-key"
    issuer = "homegym-api"
    audience = "homegym-users"
    realm = "homegym"
  }

  application {
    modules = [ com.homegym.ApplicationKt.module ]
  }
}
